#!/usr/bin/env perl
use strict;
use warnings;
use DBI;
use ConfigReader::Simple;
my $config = ConfigReader::Simple->new( '/etc/stowball.cfg' );
my $DATABASE = $config->get( 'DATABASE' );
my $dbh = DBI->connect( "dbi:SQLite:$DATABASE", "", "",	{ RaiseError => 1, AutoCommit => 1 } );
my %packages = &get_packages_hash;

my $id = 0;

# 1,Text-CSV,"CPAN module: Text::CSV",1.17,2010-03-16,2010-04-13
# 2,sqlite3,"SQLite embedded SQL database engine",3.6.23.1,2010-03-30,2010-04-16
# 3,libxml2,"The XML C parser and toolkit of Gnome",2.7.7,2010-03-15,2010-04-14
# 4,libxslt,"The XSLT C library for GNOME (provides xsltproc)",1.1.26,2009-06-10,2010-04-14
# 5,wget,"GNU Wget",1.12,2009-09-22,2010-04-16
# 6,cpio,"GNU Cpio",2.11,2010-03-10,2010-04-13
# 7,wireless_tools,"Wireless Tools for Linux",30-pre9,2009-11-24,2010-04-16
# 8,dhcpcd,dhcpcd,5.2.2,2010-03-31,2010-04-13
# 9,emacs-nox,"GNU Emacs without X support",23.1,2009-07-29,2010-04-13
# 10,rsync,rsync,3.0.7,2009-12-31,2010-04-14
# 11,DBI,"DBI: the standard database interface module for Perl",1.611,2010-03-02,2010-04-13
# 12,DBD-SQLite,"CPAN module: DBD-SQLite, Self-contained RDBMS (SQLite) in a DBI Driver",1.30_02,2010-03-30,2010-04-13
# 13,sudo,"run some (or all) commands as root",1.7.2p6,2010-04-09,2010-04-16
# 14,qt-framework,"Qt application development framework",4.6.2,2010-02-15,2010-04-14
# 15,qt-sdk,"Qt SDK: Complete Development Environment",4.6.2,2010-02-15,2010-04-14
# 16,openssl,openssl,1.0.0,2010-03-29,2010-04-14
# 17,openssh,"encrypted communication sessions",5.4p1,2010-03-08,2010-04-14
# 18,git,"free revision control",1.7.0.5,2010-03-31,2010-04-13
# 19,python3,"Python Programming Language",3.1.2,2010-03-21,2010-04-14
# 20,python,"Python Programming Language",2.6.5,2010-03-19,2010-04-14
# 21,atomic_ops,"Multiplatform library with atomic operations",7.2alpha4,2009-12-02,2010-04-13
# 22,expat,"Expat XML Parser",2.0.1,2007-06-05,2010-04-13
# 23,freetype,"Freetype font engine",2.3.12,2010-02-12,2010-04-13
# 24,ruby,Ruby,1.9.1p376,2009-12-07,2010-04-16
# 25. Rose-DB
emit_csv_deps( 25, 26, 32, 35, 43, 48, 11, 34, 33, 28, 31 );
# 26,Bit-Vector,"CPAN module: Bit vector math library",7.1,2009-09-29,2010-04-13
# 27,Carp-Clan,"CPAN module: Report errors",6.04,2009-10-24,2010-04-13
# 28. SQL-ReservedWords
emit_csv_deps( 28, 29 );
# 29. Sub-Exporter
emit_csv_deps( 29, 30, 54, 58 );
# 30. Data-OptList
emit_csv_deps( 30, 54, 58 );
# 31. Time-Clock
emit_csv_deps( 31, 0 );
# 32,Clone-PP,"CPAN module: Clone::PP - Recursively copy Perl datatypes",1.02,2003-08-28,2010-04-13
# 33. Rose-Object
emit_csv_deps( 33, 0 );
# 34. Rose-DateTime
emit_csv_deps( 34, 33, 35 );
# 35. DateTime
emit_csv_deps( 35, 38, 41, 40 );
# 36,Test-Exception,"CPAN module: Test::Exception - Test exception based code",0.29,2010-01-11,2010-04-12
# 37,Sub-Uplevel,"CPAN module: Sub::Uplevel - apparently run a function in a higher stack frame",0.22,2009-11-17,2010-04-12
# 38. DateTime-Locale
emit_csv_deps( 38, 39, 40 );
# 39,List-MoreUtils,"CPAN module: List::MoreUtils - Provide the stuff missing in List::Util",0.25_02,2009-08-01,2010-04-12
# 40,Params-Validate,"CPAN module: Params::Validate - Validate method/function parameters",0.95,2010-02-16,2010-04-12
# 41,DateTime-TimeZone,"CPAN: DateTime::TimeZone - Time zone object base class and factory",1.17,2010-04-10,2010-04-12
# 42. Class-Singleton
emit_csv_deps( 42, 0 );
# 43. DateTime-Format-MySQL
emit_csv_deps( 43, 44);
# 44. DateTime-Format-Builder
emit_csv_deps( 44, 45, 46, 47 );
# 45. Class-Factory-Util
emit_csv_deps( 45, 0 );
# 46. DateTime-Format-Strptime
emit_csv_deps( 46, 41, 40 );
# 47. Task-Weaken
emit_csv_deps( 47, 0 );
# 48. DateTime-Format-Pg
emit_csv_deps( 48, 44, 41);
# 49,ConfigReader-Simple,"CPAN module: ConfigReader-Simple",1.28,2009-06-09,2010-04-14
# 50,which,"GNU which",2.20,2008-08-06,2010-04-13
# 51,Perl-Critic,"CPAN: Critique Perl source code for best-practices",1.105_03,2010-03-21,2010-04-13
# 52,DBD-CSV,"CPAN: DBI driver for CSV files",0.28,2010-03-16,2010-04-13
# 53,Clone,"CPAN: Clone - recursively copy Perl datatypes",0.31,2010-01-19,2010-04-13
# 54,Params-Util,"CPAN: Params::Util - Simple, compact and correct param-checking functions",1.01,2010-03-17,2010-04-13
# 55,SQL-Statement,"CPAN: SQL::Statement - SQL parsing and processing engine",1.26,2010-04-10,2010-04-12
# 56,Text-CSV_XS,"CPAN: Text::CSV_XS - comma-separated values manipulation routines",0.72,2010-03-16,2010-04-12
# 57,Scalar-List-Utils,"CPAN: Scalar::Util - A selection of general-utility scalar subroutines",1.23_02,2010-03-30,2010-04-15
# 58. Sub-Install
emit_csv_deps ( 58, 0 );

sub get_packages_hash {
    my %packages;
    my $packages = $dbh->selectall_arrayref(
	"SELECT id, short_name FROM packages");
    
    foreach my $row (@{$packages}) {
	my ( $id, $short_name ) = @$row;
	$packages{ $id } = $short_name;
    }

    $packages{'0'} = 'NULL';
    
    return %packages;
}

sub emit_csv_deps {
    my ( $package_id, @deps ) = @_;
    foreach my $dep ( @deps ) {
	$id++;
	print "$id,$package_id,$dep,$packages{$package_id} => $packages{$dep}\n";
    }

}

__END__
Bit::Vector::Overload:  6.4
    Clone::PP:            0
    DateTime::Duration:   0
    DateTime::Format::MySQL:  0
    DateTime::Format::Pg:  0.11
    DBI:                  0
    perl:                 5.006000
    Rose::DateTime::Util:  0.532
    Rose::Object:         0.854
    Scalar::Util:         0
    SQL::ReservedWords:   0
    Test::More:           0
    Time::Clock:          0
r
    
