---
abstract: 'Parse, Analyze and Manipulate Perl (without perl)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Class::Inspector: 1.22
  ExtUtils::MakeMaker: 6.42
  File::Remove: 1.42
  Test::More: 0.86
  Test::NoWarnings: 0.084
  Test::Object: 0.07
  Test::SubCalls: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PPI
name: PPI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Clone: 0.30
  Digest::MD5: 2.35
  File::Spec: 0.84
  IO::String: 1.07
  List::MoreUtils: 0.16
  List::Util: 1.20
  Params::Util: 1.00
  Storable: 2.17
  Task::Weaken: 0
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/PPI
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/PPI
version: 1.211_01
